baseurl = "/"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

defaultContentLanguage = "de"
removePathAccents = "true"

# secuirty configuration needed since hugo 0.91, since we access the context
[security]
  [security.funcs]
    getenv = ['^HUGO_', 'CONTEXT', 'URL']

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    languageCode = "de-ch"
    contentDir = "content/de"
    title = "Cloud Native Trainings Schweiz - acend gmbh"
    # meta description
    author = "acend gmbh"
    description = "acend bietet dir praxisorientierte Cloud Native Trainings, bei denen dir mehr als nur das technische Know-how in Erinnerung bleiben wird. Von Engineers für Engineers."

    # menu
    [[languages.de.menu.main]]
    URL = "/trainings/"
    name = "Trainings"
    weight = 1

    [[languages.de.menu.main]]
    URL = "/ueber-uns/"
    name = "Über uns"
    weight = 2
    
    [[languages.de.menu.main]]
    URL = "/kontakt/"
    name = "Kontakt"
    weight = 3
 
  [languages.en]
    languageCode = "en-en"
    contentDir = "content/en"
    title = "Cloud Native Trainings Switzerland - acend gmbh"
    languageName = "English"
    weight = 2
    description = "acend offers you practice-oriented Cloud Native trainings. You will remember more than technical know-how. From Engineer to Engineer."

    # menu
    [[languages.en.menu.main]]
    URL = "/en/trainings/"
    name = "Trainings"
    weight = 1

    [[languages.en.menu.main]]
    URL = "/en/about/"
    name = "About"
    weight = 2
    
    [[languages.en.menu.main]]
    URL = "/en/contact/"
    name = "Contact"
    weight = 3


# default parameters
[params]
home = "Home"

# open graph info
twitterAccount = "@acendch"
domain = "https://acend.ch"
twitterimage = "images/acend-og.jpg"

# contact info
phone = '<a href="tel:+41313702220">+41 31 370 22 20</a>'
name = "**acend gmbh**"
address = "Sickingerstrasse 10, 3014 Bern"
email = "hello@acend.ch"


# copyright
copyright = "&copy; __YEAR__ acend gmbh"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# Formulare
[params.contact]
enable = true
form_action = "/backend/form"

# contact
[params.anmeldung]
enable = true
form_action = "/backend/form"

# social site
[params.social]
linkedin = "https://www.linkedin.com/company/acendch/"
twitter = "https://www.twitter.com/acendch"
youtube = "https://www.youtube.com/@acendch"

[imaging]
quality = 50
hint = "photo"