{{- $fullName := include "acend-website-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if eq .Release.Name "latest" -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "acend-website-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: acend-letsencrypt
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
  - host: acend.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  tls:
  - hosts:
    - acend.ch
    secretName: acend-ch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-www
  labels:
    {{- include "acend-website-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: acend-letsencrypt
  {{- end }}
ingressClassName: {{ .Values.ingress.ingressClass }}
spec:
  rules:
  - host: www.acend.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  tls:
  - hosts:
    - www.acend.ch
    secretName: www-acend-ch
{{ else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "acend-website-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: staging-basic-auth
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
  - host: website-{{ .Release.Name }}.test.acend.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  tls:
  - hosts:
    - website-{{ .Release.Name }}.test.acend.ch
    secretName: acend-test-wildcard
{{- end }}
