apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acend-website-chart.fullname" . }}-backend
  labels:
    {{- include "acend-website-chart.labels" . | nindent 4 }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "acend-website-chart.selectorLabels" . | nindent 6 }}
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acend-website-chart.selectorLabels" . | nindent 8 }}
        tier: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acend-website-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Release.Name }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef:
                name: acend-website-backend
                key: SMTP_HOST
          - name: SMTP_FROM
            valueFrom:
              configMapKeyRef:
                name: acend-website-backend
                key: SMTP_FROM
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: acend-website-backend
                key: SMTP_PORT
          - name: SMTP_TO
            valueFrom:
              configMapKeyRef:
                name: acend-website-backend
                key: SMTP_TO
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: acend-website-backend
                key: SMTP_USERNAME
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: acend-website-backend
                key: SMTP_PASSWORD
          - name: MAILCHIMP_API_KEY
            valueFrom:
              secretKeyRef:
                name: acend-website-backend
                key: MAILCHIMP_API_KEY
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
