apiVersion: v1
kind: Service
metadata:
  name: {{ include "acend-website-chart.fullname" . }}-backend
  labels:
    {{- include "acend-website-chart.labels" . | nindent 4 }}
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acend-website-chart.selectorLabels" . | nindent 4 }}
    tier: backend
