apiVersion: v1
kind: Service
metadata:
  labels:
    app: acend-website-staging
  name: acend-website-staging
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: acend-website-staging
  sessionAffinity: None
  type: ClusterIP
