name: Build Website

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/website-hugo:pr-${{ github.event.pull_request.number }}
      - 
        name: 'Deploy Helm Release'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'pr-${{ github.event.pull_request.number }}'
          namespace: 'acend-website-test'
          version: '${{ github.sha }}'
          chart: 'helm-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          values: |
            backendurl: http://localhost:8080

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_TEST }}'
      - 
        name: Redeploy Latest Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_TEST_BASE64 }}
        with:
          args: rollout restart deployment/pr-${{ github.event.pull_request.number }}-acend-website-acend --namespace acend-website-test
      - 
        name: Comment PR Environments in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environments: 
           * acend version <https://website-pr-${{ github.event.pull_request.number }}.training.acend.ch>
           

