name: Build Website

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/website-hugo:staging
            quay.io/acend/website-hugo:pr-${{ github.event.pull_request.number }}
      -
        name: 'Install Helm'
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2
      -
        name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.2
      -
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      -
        name: Deploy Helm Release
        env:
          WEBSITE_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
          WEBSITE_NAMESPACE: 'acend-website-test'
          WEBSITE_VERSION: '${{ github.sha }}'
        run: |
          helm upgrade --install --wait --kubeconfig $HOME/.kube/config  --namespace=$WEBSITE_NAMESPACE --set=app.name=$WEBSITE_HELM_RELEASE --set=app.version=$WEBSITE_VERSION  --values=helm-chart/values.yaml --atomic $WEBSITE_HELM_RELEASE ./helm-chart
      -
        name: Redeploy Deployments
        env:
          WEBSITE_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
          WEBSITE_NAMESPACE: 'acend-website-test'
        run: |
          kubectl rollout restart deployment/${TRAINING_HELM_RELEASE}-acend-website --kubeconfig $HOME/.kube/config --namespace $WEBSITE_NAMESPACE
      - 
        name: Comment PR Environments in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
           PR Environments: 
           * acend website <https://website-pr-${{ github.event.pull_request.number }}.test.acend.ch>
           

