name: push_main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "content *.md"
          config_file: ".markdownlint.json"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build and Push Latest Version
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/acend/website-hugo:latest
      - 
        name: 'Deploy Helm Release'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'latest'
          namespace: 'acend-website'
          version: '${{ github.sha }}'
          repository: 'https://acend.github.io/helm-charts/'
          chart: 'helm-chart'
          token: '${{ github.token }}'
          helm: 'helm3'
          values: |
            backendurl: http://acend-website-backend:8000

        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      - 
        name: Redeploy Prod Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: rollout restart deployment/latest-acend-website --namespace acend-website
